spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3311/spring
spring.datasource.username=root
spring.datasource.password=StrTit24815032006*

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
