spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_HOST:jdbc:mysql://localhost:3306/teste}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:senha123}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
