spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3311/spring
    username: root
    password: StrTit24815032006*
  jpa:
    hibernate:
      ddl-auto: create-drop  # Use 'update', 'create', 'create-drop' ou 'none' conforme necessário
    show-sql: false
