spring.jackson.time-zone=America/La_Paz
spring.profiles.active=h2
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pasajesboliviabaratos@gmail.com
spring.mail.password=yjet djia mndq bqbz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.test-connection=false
api.security.token.secret=${JWT_SECRET:pastaMasterChef}
api.viaje.max-time-viaje-day=3
api.viaje.min-time-before-buy-pasaje-min=30
api.thymeleaf.templates.locale=templates
api.passagem.taxa.uso = 0.1
spring.server.front-end.base_url=${BASE_URL_FRONT:http://localhost:5173}