spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_HOST:jdbc:mysql://localhost:3306/passagens}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:StrTit24815032006*}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
